Index Hebrew Rabash Assorted Notes with number
Bnei-Baruch/archive-backend pull request #208
Opened 2020-09-18 03:55 UTC by Evgeny1971

Index Hebrew Rabash Assorted Notes with number and not letter

2020-09-18 13:44 UTC, YuriHechter requested changes

2020-09-18 13:44 UTC, YuriHechter commented on es/sources_index.go
> +						breaked_parent = parent
why we need a new var 'breaked_parent'? why not to use 'parent'?

2020-09-18 13:44 UTC, YuriHechter commented on es/sources_index.go
> +					*/
remove the commented out part

2020-09-29 01:38 UTC, Evgeny1971 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Index Hebrew Rabash Assorted Notes with number and not letter](https://trello.com/c/a6fEYVG5/232-index-hebrew-rabash-assorted-notes-with-number-and-not-letter)

2020-10-02 03:16 UTC, merged