Cache search results for 1 minute. Should reduce load spikes.
Bnei-Baruch/archive-backend pull request #341
Opened 2024-02-23 03:29 UTC by bbfsdev

2024-02-24 03:27 UTC, edoshor requested changes

2024-02-24 03:27 UTC, edoshor commented on api/handlers.go
> +  if res, err = searchCache.Get(query, sortByVal, from, size); err == nil && res == nil {
If we get an error from the cache, which is not `ErrNotFound` I think we should try elastic nonetheless. The cache is not critical.

2024-02-24 03:27 UTC, edoshor commented on search/search_cache.go
> +  cache.SetTTL(time.Duration(1 * time.Minute))
Can we have this larger. Maybe 5 minutes ?

2024-02-24 03:27 UTC, edoshor commented on search/search_cache.go
> +  key := query.ToFullSimpleString(sortBy, from, size)
Is `query.ToFullSimpleString` stable enough ?
Remember that all logically equivalent queries should be mapped to exactly the same cache key

2024-02-25 05:40 UTC, closed without merging

2024-02-25 05:41 UTC, bbfsdev commented
Closed due to a different design chosen. We are going to:
1. Deprecate elastic logging
2. Use nginx caching
3. Use chronicles for logging